name: CI

on: [push, pull_request]

jobs:
  server-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install server deps
        run: |
          cd server
          npm ci
      - name: Run server tests
        run: |
          cd server
          npm test

  ui-tests:
    runs-on: ubuntu-latest
    needs: server-tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Start server
        run: |
          cd server
          npm ci
          nohup npm start &
          sleep 1
      - name: Install client deps
        run: |
          cd client
          npm ci
      - name: Run Cypress headless
        uses: cypress-io/github-action@v5
        with:
          working-directory: client
          start: npm run dev
          wait-on: 'http://localhost:5173'
          browser: chrome
